# Site settings
title: FusionInventory
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  FusionInventory website with documentation and news of this wonderful
  inventory and software deployment tool ;)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fusioninventory.github.io" # the base hostname & protocol for your site
twitter_username: fusioninventory
github_username:  fusioninventory
favicon: /images/fusioninventory.png

exclude:
    - documentation/agent/man/generate-mans.pl

paginate: 8
paginate_path: "/news/page:num/"

# Build settings
markdown: kramdown

# Used gem
gems:
    - jekyll-redirect-from
